import { tracks } from "./data/sharedModules";

export const mockRoadmaps = [
  {
    id: "1",
    title: "ServiceNow Developer / CSA",
    slug: "csa",
    description: "The complete, linear learning path to master ServiceNow from scratch to advanced development and security.",
    difficulty: "Comprehensive",
    estimatedDuration: "12 Weeks",
    certification: "Certified System Administrator (CSA)",
    prerequisites: "None",
    careerOutcome: "ServiceNow Developer",
    salaryRange: "$80k - $140k",
    phase: 1,
    unlocks: ["Certified Application Developer (CAD)"],
    learningObjectives: "Master the ServiceNow platform, learn to develop applications, automate workflows, discover infrastructure, integrate with other systems, and secure the instance.",
    color: "from-blue-600 to-blue-900",
    iconName: "Map",
    order: 1,
    modules: tracks.find(t => t.slug === 'csa')?.modules.map((mod, i) => ({
      id: mod.id,
      title: mod.title,
      description: mod.description,
      estimatedTime: mod.level,
      completed: false,
      items: mod.items
    }))
  },
  {
    id: "2",
    title: "ITOM Specialist",
    slug: "itom",
    description: "Master Configuration Management Database (CMDB), infrastructure discovery, and service mapping.",
    difficulty: "Advanced",
    estimatedDuration: "6 Weeks",
    certification: "Certified Implementation Specialist - IT Service Management (CIS-ITSM)",
    prerequisites: "CSA Certification",
    careerOutcome: "ITOM Implementer",
    salaryRange: "$100k - $160k",
    phase: 2,
    unlocks: ["Service Mapping Specialist"],
    learningObjectives: "Master the ServiceNow ITOM suite including CMDB configuration, MID Server setup, Discovery patterns, and top-down Service Mapping.",
    color: "from-cyan-600 to-cyan-900",
    iconName: "Database",
    order: 2,
    modules: tracks.find(t => t.slug === 'itom')?.modules.map((mod, i) => ({
      id: mod.id,
      title: mod.title,
      description: mod.description,
      estimatedTime: mod.level,
      completed: false,
      items: mod.items
    }))
  },
  {
    id: "3",
    title: "Javascript Developer",
    slug: "javascript",
    description: "Learn JavaScript from scratch with a focus on ServiceNow development.",
    difficulty: "Beginner",
    estimatedDuration: "4 Weeks",
    certification: "None",
    prerequisites: "None",
    careerOutcome: "ServiceNow Developer",
    salaryRange: "$80k - $140k",
    phase: 1,
    unlocks: [],
    learningObjectives: "Master JavaScript syntax, logic, and advanced concepts like arrays, objects, and REST APIs.",
    color: "from-yellow-500 to-yellow-700",
    iconName: "FileText",
    order: 3,
    modules: tracks.find(t => t.slug === 'javascript')?.modules.map((mod, i) => ({
      id: mod.id,
      title: mod.title,
      description: mod.description,
      estimatedTime: mod.level,
      completed: false,
      items: mod.items
    }))
  },
  {
    id: "4",
    title: "ServiceNow SDK Developer",
    slug: "sdk",
    description: "Learn how to build applications on ServiceNow using the ServiceNow SDK and Fluent.",
    difficulty: "Advanced",
    estimatedDuration: "4 Weeks",
    certification: "None",
    prerequisites: "JavaScript Developer",
    careerOutcome: "ServiceNow Developer",
    salaryRange: "$100k - $150k",
    phase: 3,
    unlocks: [],
    learningObjectives: "Master the ServiceNow SDK, Fluent API, and modern development workflows.",
    color: "from-indigo-600 to-indigo-900",
    iconName: "Code",
    order: 4,
    modules: tracks.find(t => t.slug === 'sdk')?.modules.map((mod, i) => ({
      id: mod.id,
      title: mod.title,
      description: mod.description,
      estimatedTime: mod.level,
      completed: false,
      items: mod.items
    }))
  },
  {
    id: "5",
    title: "App Engine Studio",
    slug: "app engine studio",
    description: "Rapidly build custom applications in ServiceNow using low-code tools in App Engine Studio.",
    difficulty: "Intermediate",
    estimatedDuration: "3 Weeks",
    certification: "Certified Application Developer (CAD)",
    prerequisites: "CSA Certification",
    careerOutcome: "Citizen Developer",
    salaryRange: "$90k - $130k",
    phase: 2,
    unlocks: [],
    learningObjectives: "Master App Engine Studio, App Engine Management Center, Flow Designer, and UI Builder.",
    color: "from-blue-500 to-blue-700",
    iconName: "Layout",
    order: 5,
    modules: tracks.find(t => t.slug === 'app engine studio')?.modules.map((mod, i) => ({
      id: mod.id,
      title: mod.title,
      description: mod.description,
      estimatedTime: mod.level,
      completed: false,
      items: mod.items
    }))
  },
  {
    id: "6",
    title: "Virtual Agent",
    slug: "virtual agent",
    description: "Build conversational interfaces and integrate NLU to deflect incidents and automate requests.",
    difficulty: "Intermediate",
    estimatedDuration: "3 Weeks",
    certification: "None",
    prerequisites: "CSA Certification",
    careerOutcome: "Automation Specialist",
    salaryRange: "$90k - $140k",
    phase: 2,
    unlocks: [],
    learningObjectives: "Design topic flows, integrate Natural Language Understanding (NLU), and configure Live Agent handoff.",
    color: "from-purple-500 to-purple-700",
    iconName: "Mic",
    order: 6,
    modules: tracks.find(t => t.slug === 'virtual agent')?.modules.map((mod, i) => ({
      id: mod.id,
      title: mod.title,
      description: mod.description,
      estimatedTime: mod.level,
      completed: false,
      items: mod.items
    }))
  }
];
